[window]
opacity = 0

[colors.primary]
background = '#13191c'
foreground = '#dbdbdb'

[colors.cursor]
text = '#dbdbdb'
cursor = '#00bef9'

[colors.normal]
black   = '#161616'
red     = '#cc2a1b'
green   = '#86c100'
yellow  = '#dea300'
blue    = '#0087de'
magenta = '#702eb6'
cyan    = '#00bef9'
white   = '#dbdbdb'

[colors.bright]
black   = '#2e2e2e'
red     = '#ed7665'
green   = '#beed7d'
yellow  = '#ffd65a'
blue    = '#47b7ff'
magenta = '#966dd1'
cyan    = '#9feaff'
white   = '#fcfcfc'

[window.padding]
x = 8
y = 8

[cursor.style]
shape = 'Beam'
blinking = 'On'
